### PR TITLE
Rewrite .travis to use stack 

### PR DESCRIPTION
**Pull request by rrnewton**
Hi @nomeata,

This new travis file aims to preserve the functionality of the original .travis setup, except it drops 7.6 support.

[The 7.10.3 build is passing fine.](https://travis-ci.org/iu-parfunc/gipeda/jobs/133369021)

In contrast, 7.8 is [currently getting a build error in gitlib-libgit2](https://travis-ci.org/iu-parfunc/gipeda/jobs/133369022), and it's the same error you are seeing on your current travis, e.g. [here](https://travis-ci.org/nomeata/gipeda/jobs/132879622).  You an decide whether you want to debug that or not, but I've marked it as an allowed failure for now.

This setup aims to test five different configs:
- deterministic: Stackage 7.10 series
- deterministic: Stackage 7.8 series (lts-2.22) -- currently broken
- nondeterministic: Stackage nightly -- track the current stackage, currently GHC 8.0 and failing.  Some work is needed to support 8.0.
- nondeterministic: ghc-7.10 resolver -- i.e. use the latest packages and see what breaks
- nondeterministic: ghc-7.8 resolver -- i.e. use the latest packages and see what breaks

Travis does not directly test the docker file.  Travis could do that, but then you must run in a full VM and lose the ability to cache `~/.stack`.  Also, it becomes a real pain to vary the settings as above.  It would amount to a bunch of inplace sed hacks on the Dockerfile, or generation of multiple Dockerfiles.

The Dockerfile is designed for a different purpose currently -- giving a binary distribution where people can get the gipeda executable trivially.  And then build their own websites reproducibly inside a container.

The better test for the Dockerfile is whether the automated builds on Dockerhub are building.  E.g. [here is the build history for this fork](https://hub.docker.com/r/parfunc/gipeda/builds/).  Unfortunately, the support for "badges" for dockerhub is currently a hack.

For tagging Docker images, I would like to use the same version numbers as used in the hackage releases.  In that build history you can see that I've currently named the tag "post0.2.0.1" because I know the HEAD is somewhere past that release.  Can you say exactly which commit corresponds to version 0.2.0.1 on hackage?  Is it [this one](https://github.com/nomeata/gipeda/commit/109eb1e01b3d6b68c57ce68cb8728e9b0d2d75f9)?  That was the commit that changed the version number to 0.2.0.1.

Alas, for setting up Dockerhub automated builds for `nomeata/gipeda` I cannot help you.  It seems it has the same problem as travis, which I think is based on a common github limitation.  Collaborators, weirdly, can't have "admin" access.  Thus my dockerhub account, authenticated as me on github, can't set anything up automatically.  Not unless the repo is moved to an organization and I'm granted admin perms on it.

But if you want to set up builds of `nomeata/gipeda` directly, it is really trivial.  Just as easy as travis.  Just make a `nomeata` account, connect to your github, and click "Create Automated Build" at the top right.  Then just click on the name of the repo, and you're good to go.

### CODE REVIEW

**Comment by nomeata** [comment]
Great, thanks!

I think I forgot to tag that particular commit. But let me just push a new release to hackage. Anything trivial I should include before pushing?

Registering at hub.docker.com right now....

**Comment by nomeata** [comment]
https://hub.docker.com/r/nomeata/gipeda/ exists now.

**Comment by rrnewton** [comment]
Thanks!  

It would be great to have a new release.  I couldn't get a website built with 0.2.0.1 which is currently in Stackage as well as hackage.

Naming tags just plain "X.Y.Z" seems to be the convention for dockerhub.  I.e. `ubuntu/14.04`.  IMHO Dockerhub provides an extra incentive to treat tags as immutable... E.g. I plan to have downstream Dockerfiles that depend on `nomeata/gipeda:0.2.1` or whatever.

**Comment by nomeata** [comment]
Uploaded as 0.3.

**Pull request merged**
