### PR TITLE
Add a dockerfile and stack.yaml

### PR DESCRIPTION
**Pull request by rrnewton**
This makes it much easier for new users to build it!

### CODE REVIEW

**Comment by nomeata** [comment]
Thanks. Would you be willing to expand the `.travis.yaml` file to test these files, so that they stay functional?

**Comment by rrnewton** [comment]
Sure, and along with that it would be good to create an auto-build for Dockerhub.  I pushed one manually here:

   https://hub.docker.com/r/parfunc/gipeda/

Could you do that, or if you don't have a dockerhub account -- if you make me a contributor on the main repo I could set up the auto-build there.

**Comment by nomeata** [comment]
You got contributors rights. Feel free to mess with everything around stack and docker directly; for other non-trivial changes I’m happy to still review PRs for now.

**Comment by rrnewton** [comment]
Yes, of course -- thanks.  I think that lets me set up the hooks to dockerhub auto-build.  I set up on auto-build here for our fork, let me try to change it to the main repo:

  https://hub.docker.com/r/parfunc/gipeda/builds/

**Comment by nomeata** [comment]
I’m quite ignorant with Dockerhub etc (I only ab-used docker so far :-)), so if there is anything of interest to users (e.g. alternative installation options), please do add it to the README.

**Comment by rrnewton** [comment]
Ok, see #42 for the travis.yam changes.

**Pull request merged**
